version: '3'
services:
  dispatcher:
    build: .
    image: dispatcher
    volumes:
      - .:/go/src/github.com/upsub/dispatcher
    ports:
      - '4400:4400'
    environment:
      - NATS_HOST=nats
      - NATS_PORT=4222
    links:
      - nats

  nats:
    image: "nats:latest"
    ports:
      - '4222:4222'
