[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
